### ISSUE TITLE
Is your LICENSE truly custom?

### ISSUE THREAD

**Issue by yyyc514** [highlightjs/highlightjs-xtlang#4]
If you're using one of the standard OSS licenses could you please add that so it's clear? Or are you truly using a custom license?

**Comment by benswift** [comment]
I'm not sure if I understand - there's a BSD 3-clause in `LICENCE.md`? Or are you referring to the re-wording of the 3rd clause to name-drop hljs instead of just saying "the copyright holder"?

I don't _think_ the intention was to have a custom licence; just to be a good citizen with regard to the parent project. @cyblue9 does that track with you?

**Comment by yyyc514** [comment]
Typically the first line of the license file tells you what the license is.  This is usually true of BSD licenses also.  But your license seems to be missing that first line for some reason.  That was what led to me posting this issue.

**Comment by cyblue9** [comment]
Sorry for late reply.

This is the BSD 3-clause. I mistook how to write LICENCE.md. Sorry.

**Comment by cyblue9** [comment]
I fixed LICENCE.md. (https://github.com/highlightjs/highlightjs-xtlang/blob/master/LICENSE)

@yyyc514 @benswift 
Is this OK?

**Comment by yyyc514** [comment]
<img width="383" alt="Screen Shot 2020-01-06 at 10 17 43 AM" src="https://user-images.githubusercontent.com/6473/71827231-cbfac800-306d-11ea-9bc9-fde68230b0eb.png">

Nice, and now Github can identify your license also!

**Comment by benswift** [comment]
Yep, ok by me.
